name: dmeister
labels:
  stack: python
  squad: infrastructure

no_ops: True
expose: True
healthcheck_url: /heartbeat
port: 8080

environment:
  default:
    GOOGLE_ORG: canopytax.com
    DATABASE_MAX_POOL_SIZE: 12
    DATABASE_USER: dmeister_app
    DATABASE_DB_NAME: dmeisterdb
    SKIP_MIGRATIONS: true
    COOKIE_NAME: canopydiscovermeister
  integ:
    ENV_LOCATION: integ
  stage:
    ENV_LOCATION: stage
  production:
    COOKIE_NAME: canopydiscovery
    ENV_LOCATION: production

secrets:
  dmeister:
    GOOGLE_ID: google_id
    GOOGLE_SECRET: google_secret
    COOKIE_KEY: cookie_key
    SENTRY_URL: sentry_dsn
  database-creds:
    DATABASE_URL: dmeister_hostname
    DATABASE_PASS: dmeister_app


migration:
  command: ["alembic", "upgrade", "head"]
  environment:
    default:
      DATABASE_MIGRATION_USER: dmeister_sa
      DATABASE_DB_NAME: dmeisterdb
  secrets:
    database-creds:
      DATABASE_URL: dmeister_hostname
      DATABASE_MIGRATION_PASS: dmeister_sa
