version: '3.7'
services:
  postgres:
    image: postgres:11-alpine
    ports:
      - 5432:5432
      -
  dmeister:
    image: canopytax/dmeister
    volumes:
      - ./dmeister:/app/dmeister
    environment:
      DATABASE_URL: postgres
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
      DATABASE_DB_NAME: postgres
      DEBUG: "true"
      AIOHTTP_NOSENDFILE: "true"
      IS_LOCAL: "true"
      COOKIE_KEY: 02a6b302c4290605f440baba456f954d
    ports:
      - 8080:8080
