"""add stripped path to endpoints

Revision ID: 9d7502e48303
Revises: 74b07841b893
Create Date: 2019-10-18 14:38:35.300124

"""

# revision identifiers, used by Alembic.
revision = '9d7502e48303'
down_revision = '74b07841b893'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa

from dmeister.dataaccess import db
from dmeister.models import Endpoint


def upgrade():
    # ### commands auto generated by Alembic ###
    op.add_column('endpoints', sa.Column('stripped_path', sa.String(), nullable=True))
    op.create_index(op.f('ix_endpoints_stripped_path'), 'endpoints', ['stripped_path'], unique=False)
    op.create_unique_constraint(None, 'services', ['name'])
    op.execute('ALTER TABLE services DROP COLUMN IF EXISTS squad;')
    # ### end Alembic commands ###

    bind = op.get_bind()
    endpoints = bind.execute(db.endpoints.select())
    for row in endpoints:
        ep = Endpoint.from_db(row)
        bind.execute(db.endpoints.update().values(stripped_path=ep.stripped_path)
                     .where(path=ep.path))


def downgrade():
    # ### commands auto generated by Alembic ###
    op.drop_index(op.f('ix_endpoints_stripped_path'), table_name='endpoints')
    op.drop_column('endpoints', 'stripped_path')
    # ### end Alembic commands ###
